apiVersion: v1
kind: Service
metadata:
  name: {{ include "ilanas-website.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "ilanas-website.fullname" . }}
