name: Docker Image CI
#ilana
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_TAG="ilanasm/ilanas-test:$(date +%Y-%m-%d)"
        docker build . --file DockerFile --tag $IMAGE_TAG
    
    - name: Push the Docker image
      run: |
        IMAGE_TAG="ilanasm/ilanas-test:$(date +%Y-%m-%d)"
        docker push $IMAGE_TAG

    - name: Update Helm chart values
      run: |
        IMAGE_TAG="ilanasm/ilanas-test:$(date +%Y-%m-%d)"
        sed -i "s|repository: .*|repository: \"$IMAGE_TAG\"|" ./ilana/values.yaml

    - name: Commit updated Helm chart
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add ./ilanas-website/values.yaml
        git commit -m "Update Helm chart with image version $IMAGE_TAG"
        git push
